version: "3.8"

services:
  app:
    build: .
    container_name: leisure-link-backend
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/leisurelink
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    volumes:
      - ./target/leisure-link.jar:/target/leisure-link.jar
    depends_on:
      - postgres
    command: java -jar /target/leisure-link.jar


  postgres:
    image: postgres:13
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: leisurelink

